### PR TITLE
Creating a basic Renting Contract

### PR DESCRIPTION
**Pull request by Alonzo-Coeus**
A basic contract to allow a land owner to rent out land to a tenent.

### CODE REVIEW

**Comment by martriay** [comment]
Interesting approach! A few observations:

- It would be nice if the owner could update the prices
- You should use the [ownable](https://github.com/OpenZeppelin/zeppelin-solidity/blob/master/contracts/ownership/Ownable.sol) contract to handle ownership (take advantage of the `onlyOwner` modifier!)
- How does `updateTokenMetadata` works if the land's ownership is never transferred?

**Comment by Alonzo-Coeus** [comment]
1) can do
2) so can we know what the address of a contract will be before submission the init is their to activate the contact once it has land.
3) yes i think i should use that
4) that is the whole point of the InitRentContract to insure that the contract has the land

**Comment by eordano** [comment]
Great job @Alonzo-Coeus, I'll review later and give you some feedback!

**Comment by martriay** [comment]
@Alonzo-Coeus wouldn't be easier if the constructor transferred the land ownership on creation?
Right now, as `InitRentContract` isn't a `onlyOwner` method, anyone can call the method and change the `land`.

**Comment by Alonzo-Coeus** [comment]
@martriay nice catch

**Pull request merged**
